### ISSUE TITLE
Feature Request - Wildcard Search

### ISSUE THREAD

**Issue by Heimdall-One** [unbekanntes-pferd/dcprov#2]
Function, where you can search for example for a whole mail domain.

Example:

./dcprov list https://dracoon.team -f userLogin:eq:*@mustermann.de

**Comment by unbekanntes-pferd** [comment]
The filter of GET /provisioning/customers does not allow a wildcard or cn search for userLogin, the filter is always an exact match (eq). No implementation possible - close.
